sudo: required
services:
  - docker

notifications:
  slack: privateuser-workspace:5hybgvvnXJOVAuc01WiKfrmX # for slack notifications describing build status

before_install:
  - docker build -t adriankubica/rest_api -f ./services/rest/Dockerfile.dev ./services/rest # run integration tests while repository is pushed to Github

script:
  - docker run adriankubica/rest_api sh -c "flake8 && pytest && pytest --cov"

after_success:
  - docker build -t adriankubica/rest-rest_api ./services/rest
  - docker build -t adriankubica/rest-nginx ./services/nginx
  # Log in to the docker CLI
  - docker login -u "$DOCKER_ID" -p "$DOCKER_PASSWORD"
  # Take thos images and push them to docker hub
  - docker push adriankubica/rest-rest_api
  - docker push adriankubica/rest-nginx