version: '3'
services:
  # Definition for nginx server
  nginx:
    build:
      dockerfile: Dockerfile.dev
      context: ./services/nginx
    restart: always
    volumes:
      - ./services/rest/static:/static
    ports:
      - 80:80
    depends_on:
      - rest
  # Definition for redis service
  redis:
    image: redis:latest
    restart: always
  # Definition for rest service
  rest:
    build:
      dockerfile: Dockerfile.dev
      context: ./services/rest
    restart: always
    volumes:
      - ./services/rest:/rest
    environment:
      - GITHUB_USER=somegithubtestuser
      - GITHUB_PASSWORD=somegithubtestpassword
    depends_on:
      - redis