FROM python:3.7
LABEL maintainer="adrian.kubica.ak@gmail.com"

ENV PYTHOUNBUFFERED 1

RUN apt-get update
ENV TZ Europe/Warsaw

WORKDIR /rest
COPY Pipfile Pipfile.lock ./
RUN pip install pipenv
RUN pipenv install --dev --system
COPY ./ ./

CMD ["gunicorn", "--config", "gunicorn_config.py", "--reload", "app.wsgi"]